[project]
name = "food-suggestion-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Naeem Mubarak", email = "naeemmubarak777@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "groq>=1.6.0",
    "langchain-google-genai>=4.3.4",
    "langgraph>=1.2.11",
    "langgraph-checkpoint-postgres>=3.1.2",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.3",
    "soundfile>=0.14.0",
    "uvicorn>=0.52.4",
    "websockets>=15.0.1",
]

[tool.uv]
package = false

[dependency-groups]
dev = []
